# PIPELINE DEFINITION
# Name: code-understanding-pipeline
# Description: Clone repo, generate GraphRAG metadata, build index, and tar output
# Inputs:
#    chunk_overlap: int [Default: 0.0]
#    chunk_size: int [Default: 0.0]
#    git_branch: str [Default: 'main']
#    git_repo: str [Default: '']
#    graphrag_source_path: str [Default: 'graph_rag_app/source']
#    languages: str [Default: '']
#    max_concurrency: int [Default: 0.0]
#    n_completions: int [Default: 0.0]
#    pvc_name: str [Default: '']
#    repo_ref: str [Default: 'main']
#    repo_url: str [Default: '']
#    source_path: str [Default: 'source']
#    target_path: str [Default: 'target']
components:
  comp-data-generation-step:
    executorLabel: exec-data-generation-step
    inputDefinitions:
      parameters:
        git_branch:
          parameterType: STRING
        git_repo:
          parameterType: STRING
        languages:
          parameterType: STRING
        max_concurrency:
          parameterType: NUMBER_INTEGER
        n_completions:
          parameterType: NUMBER_INTEGER
        source_path:
          parameterType: STRING
        target_path:
          parameterType: STRING
  comp-data-indexing-step:
    executorLabel: exec-data-indexing-step
    inputDefinitions:
      parameters:
        chunk_overlap:
          parameterType: NUMBER_INTEGER
        chunk_size:
          parameterType: NUMBER_INTEGER
        codebase_path:
          parameterType: STRING
        graphrag_source_path:
          parameterType: STRING
  comp-export-index-artifact:
    executorLabel: exec-export-index-artifact
    inputDefinitions:
      parameters:
        workdir:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        index_artifact:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
  comp-git-clone-step:
    executorLabel: exec-git-clone-step
    inputDefinitions:
      parameters:
        repo_ref:
          parameterType: STRING
        repo_url:
          parameterType: STRING
  comp-tar-step:
    executorLabel: exec-tar-step
    inputDefinitions:
      parameters:
        graphrag_source_path:
          parameterType: STRING
        target_path:
          parameterType: STRING
deploymentSpec:
  executors:
    exec-data-generation-step:
      container:
        args:
        - 'import papermill as pm, sys; mc, nc = int(sys.argv[6]), int(sys.argv[7]);
          langs = [x.strip() for x in sys.argv[5].split(",")] if sys.argv[5] else
          None; params = {"_GIT_REPO": sys.argv[1], "_GIT_BRANCH": sys.argv[2], "_SOURCE_PATH":
          sys.argv[3], "_TARGET_PATH": sys.argv[4]}; params.update({k: v for k, v
          in [("_LANGUAGES", langs), ("_MAX_CONCURRENCY", mc), ("_N_COMPLETIONS",
          nc)] if v}); pm.execute_notebook("/opt/app-root/src/workflows/code_understanding/data_generation_graphrag_pipeline.ipynb",
          "/dev/null", cwd="/opt/app-root/src/workflows/code_understanding", log_output=True,
          progress_bar=False, parameters=params)'
        - '{{$.inputs.parameters[''git_repo'']}}'
        - '{{$.inputs.parameters[''git_branch'']}}'
        - '{{$.inputs.parameters[''source_path'']}}'
        - '{{$.inputs.parameters[''target_path'']}}'
        - '{{$.inputs.parameters[''languages'']}}'
        - '{{$.inputs.parameters[''max_concurrency'']}}'
        - '{{$.inputs.parameters[''n_completions'']}}'
        command:
        - python3
        - -c
        image: quay.io/midawson/agent-mesh-for-sw-modernization-data-generation:0.0.1-dev
    exec-data-indexing-step:
      container:
        args:
        - 'import papermill as pm, sys; cs, co = int(sys.argv[3]), int(sys.argv[4]);
          params = {"_CODEBASE_PATH": sys.argv[1], "_GRAPHRAG_SOURCE_PATH": sys.argv[2]};
          params.update({k: v for k, v in [("_CHUNK_SIZE", cs), ("_CHUNK_OVERLAP",
          co)] if v}); pm.execute_notebook("/opt/app-root/src/workflows/code_understanding/data_indexing_graphrag_pipeline.ipynb",
          "/dev/null", cwd="/opt/app-root/src/workflows/code_understanding", log_output=True,
          progress_bar=False, parameters=params)'
        - '{{$.inputs.parameters[''codebase_path'']}}'
        - '{{$.inputs.parameters[''graphrag_source_path'']}}'
        - '{{$.inputs.parameters[''chunk_size'']}}'
        - '{{$.inputs.parameters[''chunk_overlap'']}}'
        command:
        - python3
        - -c
        image: quay.io/midawson/agent-mesh-for-sw-modernization-data-indexing:0.0.1-dev
    exec-export-index-artifact:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - export_index_artifact
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.16.1'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef export_index_artifact(workdir: str, index_artifact: dsl.Output[dsl.Artifact]):\n\
          \    import shutil\n    shutil.copy(f\"{workdir}/graphrag-index.tar.gz\"\
          , index_artifact.path)\n\n"
        image: python:3.9-slim
    exec-git-clone-step:
      container:
        args:
        - git config --global --add safe.directory /opt/app-root/src && if [ -n "$GIT_TOKEN"
          ]; then git config --global credential.helper '!f() { echo username=$GIT_USERNAME;
          echo password=$GIT_TOKEN; }; f'; fi && git -C /opt/app-root/src init &&
          git -C /opt/app-root/src remote add origin {{$.inputs.parameters['repo_url']}}
          && git -C /opt/app-root/src fetch origin {{$.inputs.parameters['repo_ref']}}
          && git -C /opt/app-root/src checkout -B {{$.inputs.parameters['repo_ref']}}
          FETCH_HEAD
        command:
        - sh
        - -c
        image: quay.io/midawson/agent-mesh-for-sw-modernization-data-generation:0.0.1-dev
    exec-tar-step:
      container:
        args:
        - cd /opt/app-root/src/workflows/code_understanding && tar -czf graphrag-index.tar.gz
          --exclude={{$.inputs.parameters['graphrag_source_path']}}/settings.yaml
          {{$.inputs.parameters['graphrag_source_path']}}/ {{$.inputs.parameters['target_path']}}/
        command:
        - sh
        - -c
        image: registry.access.redhat.com/ubi9
pipelineInfo:
  description: Clone repo, generate GraphRAG metadata, build index, and tar output
  name: code-understanding-pipeline
root:
  dag:
    tasks:
      data-generation-step:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-generation-step
        dependentTasks:
        - git-clone-step
        inputs:
          parameters:
            git_branch:
              componentInputParameter: git_branch
            git_repo:
              componentInputParameter: git_repo
            languages:
              componentInputParameter: languages
            max_concurrency:
              componentInputParameter: max_concurrency
            n_completions:
              componentInputParameter: n_completions
            source_path:
              componentInputParameter: source_path
            target_path:
              componentInputParameter: target_path
        taskInfo:
          name: data-generation-step
      data-indexing-step:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-data-indexing-step
        dependentTasks:
        - data-generation-step
        inputs:
          parameters:
            chunk_overlap:
              componentInputParameter: chunk_overlap
            chunk_size:
              componentInputParameter: chunk_size
            codebase_path:
              componentInputParameter: target_path
            graphrag_source_path:
              componentInputParameter: graphrag_source_path
        taskInfo:
          name: data-indexing-step
      export-index-artifact:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-export-index-artifact
        dependentTasks:
        - tar-step
        inputs:
          parameters:
            workdir:
              runtimeValue:
                constant: /opt/app-root/src/workflows/code_understanding
        taskInfo:
          name: export-index-artifact
      git-clone-step:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-git-clone-step
        inputs:
          parameters:
            repo_ref:
              componentInputParameter: repo_ref
            repo_url:
              componentInputParameter: repo_url
        taskInfo:
          name: git-clone-step
      tar-step:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-tar-step
        dependentTasks:
        - data-indexing-step
        inputs:
          parameters:
            graphrag_source_path:
              componentInputParameter: graphrag_source_path
            target_path:
              componentInputParameter: target_path
        taskInfo:
          name: tar-step
  inputDefinitions:
    parameters:
      chunk_overlap:
        defaultValue: 0.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      chunk_size:
        defaultValue: 0.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      git_branch:
        defaultValue: main
        isOptional: true
        parameterType: STRING
      git_repo:
        defaultValue: ''
        isOptional: true
        parameterType: STRING
      graphrag_source_path:
        defaultValue: graph_rag_app/source
        isOptional: true
        parameterType: STRING
      languages:
        defaultValue: ''
        isOptional: true
        parameterType: STRING
      max_concurrency:
        defaultValue: 0.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      n_completions:
        defaultValue: 0.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      pvc_name:
        defaultValue: ''
        isOptional: true
        parameterType: STRING
      repo_ref:
        defaultValue: main
        isOptional: true
        parameterType: STRING
      repo_url:
        defaultValue: ''
        isOptional: true
        parameterType: STRING
      source_path:
        defaultValue: source
        isOptional: true
        parameterType: STRING
      target_path:
        defaultValue: target
        isOptional: true
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.16.1
---
platforms:
  kubernetes:
    deploymentSpec:
      executors:
        exec-data-generation-step:
          pvcMount:
          - componentInputParameter: pvc_name
            mountPath: /opt/app-root/src
            pvcNameParameter:
              componentInputParameter: pvc_name
          secretAsEnv:
          - keyToEnv:
            - envVar: GRAPHRAG_LLM_TOKEN
              secretKey: GRAPHRAG_LLM_TOKEN
            - envVar: GRAPHRAG_LLM_ID
              secretKey: GRAPHRAG_LLM_ID
            - envVar: GRAPHRAG_LLM_API_BASE
              secretKey: GRAPHRAG_LLM_API_BASE
            - envVar: GRAPHRAG_LLM_PROVIDER
              secretKey: GRAPHRAG_LLM_PROVIDER
            - envVar: GRAPHRAG_LLM_PROVIDER_GRAPHRAG
              secretKey: GRAPHRAG_LLM_PROVIDER_GRAPHRAG
            - envVar: EMBED_LLM_TOKEN
              secretKey: EMBED_LLM_TOKEN
            - envVar: EMBED_LLM_API_BASE
              secretKey: EMBED_LLM_API_BASE
            - envVar: EMBED_LLM_ID
              secretKey: EMBED_LLM_ID
            - envVar: EMBED_LLM_PROVIDER
              secretKey: EMBED_LLM_PROVIDER
            - envVar: EMBED_LLM_PROVIDER_GRAPHRAG
              secretKey: EMBED_LLM_PROVIDER_GRAPHRAG
            optional: false
            secretName: code-understanding-env
            secretNameParameter:
              runtimeValue:
                constant: code-understanding-env
        exec-data-indexing-step:
          pvcMount:
          - componentInputParameter: pvc_name
            mountPath: /opt/app-root/src
            pvcNameParameter:
              componentInputParameter: pvc_name
          secretAsEnv:
          - keyToEnv:
            - envVar: GRAPHRAG_LLM_TOKEN
              secretKey: GRAPHRAG_LLM_TOKEN
            - envVar: GRAPHRAG_LLM_ID
              secretKey: GRAPHRAG_LLM_ID
            - envVar: GRAPHRAG_LLM_API_BASE
              secretKey: GRAPHRAG_LLM_API_BASE
            - envVar: GRAPHRAG_LLM_PROVIDER
              secretKey: GRAPHRAG_LLM_PROVIDER
            - envVar: GRAPHRAG_LLM_PROVIDER_GRAPHRAG
              secretKey: GRAPHRAG_LLM_PROVIDER_GRAPHRAG
            - envVar: EMBED_LLM_TOKEN
              secretKey: EMBED_LLM_TOKEN
            - envVar: EMBED_LLM_API_BASE
              secretKey: EMBED_LLM_API_BASE
            - envVar: EMBED_LLM_ID
              secretKey: EMBED_LLM_ID
            - envVar: EMBED_LLM_PROVIDER
              secretKey: EMBED_LLM_PROVIDER
            - envVar: EMBED_LLM_PROVIDER_GRAPHRAG
              secretKey: EMBED_LLM_PROVIDER_GRAPHRAG
            optional: false
            secretName: code-understanding-env
            secretNameParameter:
              runtimeValue:
                constant: code-understanding-env
        exec-export-index-artifact:
          pvcMount:
          - componentInputParameter: pvc_name
            mountPath: /opt/app-root/src
            pvcNameParameter:
              componentInputParameter: pvc_name
        exec-git-clone-step:
          pvcMount:
          - componentInputParameter: pvc_name
            mountPath: /opt/app-root/src
            pvcNameParameter:
              componentInputParameter: pvc_name
          secretAsEnv:
          - keyToEnv:
            - envVar: GIT_USERNAME
              secretKey: GIT_USERNAME
            - envVar: GIT_TOKEN
              secretKey: GIT_TOKEN
            optional: false
            secretName: git-credentials
            secretNameParameter:
              runtimeValue:
                constant: git-credentials
        exec-tar-step:
          pvcMount:
          - componentInputParameter: pvc_name
            mountPath: /opt/app-root/src
            pvcNameParameter:
              componentInputParameter: pvc_name
